version: 2
jobs:
  build:
    docker:
      - image: cimg/node:20.4.0
        user : root  
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Set execute permissions for binaries
          command: chmod +x ./node_modules/.bin/*    
      - run:
          name: Run tests
          command: npm test